💄 add color palette in global css
m-wiemers/aussicamp pull request #1
Opened 2021-03-15 09:57 UTC by m-wiemers

2021-03-16 15:29 UTC, RonjaMeinecke approved these changes
Good job 🚀

2021-03-16 15:29 UTC, RonjaMeinecke commented on components/icons/LoupeIcon.tsx
> +const LoupeIcon = () => (
```suggestion
const SearchIcon = () => (
```

2021-03-16 15:29 UTC, RonjaMeinecke commented on components/icons/LoupeIcon.tsx
> +const LoupeIcon = () => (
ist vielleicht klarer als loupe 🤷🏽‍♀️

2021-03-16 17:13 UTC, fre-ben commented on styles/globals.css
> +  font-size: 16px;
You could also use `em` units instead of using fixed pixel sizes

2021-03-16 17:17 UTC, fre-ben requested changes

2021-03-16 17:17 UTC, fre-ben commented on components/button/Button.module.css
> +  padding: 15px;
Might be better to commit to one unit (pt, em, px) for every property

2021-03-16 17:18 UTC, fre-ben requested changes

2021-03-16 17:18 UTC, fre-ben commented on components/button/Button.module.css
>    padding: 15px;
Might be better to commit to one unit (pt, em, px) for every property

2021-03-16 17:23 UTC, fre-ben commented on components/icons/AussiLogoTent.tsx
> +export default AussiTentIcon;
Is it necessary to create a component, or could you also just use an img tag with the svg as source?

2021-03-16 17:27 UTC, fre-ben reviewed
GJ 💯

2021-03-16 20:29 UTC, m-wiemers commented on components/icons/AussiLogoTent.tsx
> +export default AussiTentIcon;
Yes, you are right. An img tag would also work, but this way I can change the color directly in CSS ;-)

2021-03-16 20:30 UTC, m-wiemers commented on components/button/Button.module.css
>    padding: 15px;
Good point. I will change this ;-)

2021-03-17 10:08 UTC, lmachens reviewed
Good job 🚀

2021-03-17 10:08 UTC, lmachens commented on styles/globals.css
> +@import url("https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&display=swap");
You can reduce the import to a single line. Google fonts supports to load multiple fonts at the same time.

Example:
`@import url('https://fonts.googleapis.com/css2?family=Lato&family=Montserrat&display=swap');`

2021-03-17 10:08 UTC, lmachens commented on pages/index.tsx
> +        <DateInput label="When does it start?" />
It's not required to add your components to your page in this step. We have storybook to develop components in isolation. Here, it's not isolated.

2021-03-17 10:08 UTC, lmachens commented on components/logo/Logo.tsx
> +import AussiTentIcon from "../icons/AussiLogoTent";
I would try to avoid different names.
```suggestion
import AussiTentIcon from "../icons/AussiTentIcon";
```

or
```suggestion
import AussiLogoTent from "../icons/AussiLogoTent";
```

2021-03-17 10:08 UTC, lmachens commented on components/icons/AussiLogoTent.tsx
> +      data-name="Icon map-campground"
These properties are export artifacts. You can remove them.
It's possible to automatize this by using SVG cleaner/minifier tools.

2021-03-17 10:08 UTC, lmachens commented on components/logo/Logo.tsx
> +      </span>
You don't need an `span` here. Instead, you can style the `AussiTentIcon`.
This is possible if you add `className` as property (don't forget to forward `className` to the `svg` inside of `AussiTentIcon`.

2021-03-17 10:08 UTC, lmachens commented on components/logo/Logo.tsx
> +      <p className={styles.logotext}>ussiCamp</p>
`logotext` are two words (`logoText`?)

2021-03-17 10:08 UTC, lmachens commented on components/logo/Logo.tsx
> +      {subTitle && <p className={styles.subtitle}>plan your next adventure</p>}
`subTitle` or `subtitle`?

2021-03-17 10:08 UTC, lmachens commented on components/logo/Logo.module.css
> +}
You don't need a `grid` here. Actually, it's getting more complex with a grid :). 

Try this HTML and remove all grid related properties.
```html
<div>
  <div>
    <svg><path></path></svg>ussiCamp
  </div>
  <p>plan your next adventure</p>
</div>
```

2021-03-17 10:08 UTC, lmachens commented on components/input/SearchInput.stories.tsx
> +Search.args = {};
There are stories missing demonstrating how your `SearchInput` looks like on different states.
e.g. with/without placeholder. This will force you to add properties like `value` and `onChange`.

https://5ccbc373887ca40020446347-qbeeoghter.chromatic.com/?path=/story/forms-input--basic
https://circuit.sumup.com/?path=/story/forms-input-searchinput--base

2021-03-17 10:08 UTC, lmachens commented on components/input/SearchInput.stories.tsx
> +  title: "Common/Input",
```suggestion
  title: "Common/SearchInput",
```

2021-03-17 10:08 UTC, lmachens commented on components/input/SearchInput.module.css
> +  grid-template-columns: 85% 15%;
The icon and input increases in height because of the `15%`.

2021-03-17 10:08 UTC, lmachens commented on components/icons/SearchIcon.tsx
> +    <g>
This group is not necessary. 

```suggestion
   
```

2021-03-18 09:35 UTC, lmachens reviewed
good job!!

2021-03-18 09:35 UTC, lmachens commented on components/DateInput/DateInput.tsx
> +        onChange={onDateSelect}
`value` is missing if you like to control the input

2021-03-18 09:35 UTC, lmachens commented on components/DateInput/DateInput.tsx
> +      />
It would be nice to connect the label and input. 
This allows users to focus the input if they click on the label.

Example:
```html
<label>Do you like peas?
  <input type="checkbox" name="peas">
</label>
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

2021-03-18 09:35 UTC, lmachens commented on components/DateInput/DateInput.module.css
> +}
You set the same class multiple times.
Maybe style all `label` elements in your `global.css` or outsource this class to a different CSS module.

2021-03-18 09:35 UTC, lmachens commented on components/citieSelect/SelectCity.tsx
> +        </option>
There are two issues here.

1) `value={value}` should be `value[0]`, otherwise it will target the whole array.
2) It's limited to 3 items. You could use a `.map` here. https://reactjs.org/docs/lists-and-keys.html

2021-03-18 20:07 UTC, merged